dist: trusty
language: java
os: linux
jdk: openjdk17
services:
  - postgresql
cache:
  - directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.sonar/cache/
after_success:
  - bash <(curl -s https://codecov.io/bash)
addons:
  sonarcloud:
    organization: emerson-matos

jobs:
  include:
    - stage: sonar
      script: ./gradlew sonar
      if: type = pull_request

notifications:
  slack:
    secure: ISruP6uQyGxTpEx7Y9iCrkl4mhVELf1mOwmj5KL96seoA2onuAbvhkfVoSfNCVTlM+2j5OIAa5rVkbee2BtNWsCdlNnZ2UbHxIeC+PQoyFRYa9Nu3Bf9dTi/g125hbU4j3qsFHXznehzlzshktDEray9VDgfh0O0BXM1c3kbsiq9cKvbCLgjCqpvkajivpo6W6P77228hAvM/CDpsWUMN8cSbhfPqcJDC793iVILkBv87RK5d7s98iJBgtFr3ys1cHn0MdEiCiKbZS7NDWvG7LQdicyn3TiraNRgWQ3uGnpXga1l+ifbSkQCSu6w4zZssDfVPsR3INIHh68O4AswrPzTPex9XJ68/k26Lez/OuDOGI/bUL96nW3xJ+FIHB4FrkrntJfEVXJIhctP8UBPjoMi8eesF/nku3PJiTjMjMey/Qt59vKpE26lU0JEhGYcYg1BlmrEMWROngw+3iZvkbFuUnNRwsBfsZOs7pefNG4K7kGTfn9Qz9cLKcTcDej4Kg/gVlW+xoKxwcJlMTHv42sPiGu57BfDXm/QLBIlVPuzbi3as2B7eE9cL6RsJBFHWPCrWXTEdCr2WBYgbxHCfUSN0WZ32moiDQ5ZX2IqxysZY1bpacKmraDv3glQlD0xPVIatJmmiV+oEMcwaNEKBTvQWZfMd53oDN6CT77WxQM=
---
