dist: trusty
language: java
os: linux
jdk: openjdk17
services:
  - postgresql
cache:
  - directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.sonar/cache/
before_script:
  - echo "SNAPSHOT_VERSION $SNAPSHOT_VERSION"
after_success:
  - bash <(curl -s https://codecov.io/bash)
addons:
  sonarcloud:
    organization: emerson-matos
    token:
      secure: $sonarcloud_secret
jobs:
  include:
    - stage: sonar
      script: ./gradlew sonarqube
      if: type = pull_request

notifications:
  slack:
    secure: $SLACK_SECRET
---
