dist: trusty
language: java
os: linux
jdk: openjdk17
services:
  - postgresql
cache:
  - directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.sonar/cache/
before_script:
  - echo "POM $POM_VERSION"
  - echo "SNAPSHOT_VERSION $SNAPSHOT_VERSION"
  - psql -c 'create database controle;' -U $SPRING_DATASOURCE_USERNAME
after_success:
  - ./snapshot.sh
  - bash <(curl -s https://codecov.io/bash)
addons:
  sonarcloud:
    organization: emerson-matos
    token:
      secure: $sonarcloud_secret
jobs:
  include:
    - stage: unit tests
      script: mvn clean test
      if: type = commit
    - stage: unit tests
      script: mvn clean verify sonar:sonar -Dsonar.projectKey=emerson-matos_financasapi -Pcoverage
      if: type = pull_request
    - stage: package
      script: mvn clean package
      if: type != pull_request AND type != commit

notifications:
  slack:
    secure: $SLACK_SECRET
---
